### PR TITLE
v2.7.0

### PR DESCRIPTION
**Pull request by HACO8888**

### CODE REVIEW

**Comment by banahaker** [comment]
image

I think it should be "update" for better expression.

**Review by banahaker — CHANGES_REQUESTED** [review]
Please adjust the folder structure.

**Comment by HACO8888** [comment]
> image
> 
> 
> 
> I think it should be "update" for better expression.

EDIT is better in UI/UX

**Comment by banahaker** [comment]
Obviously, "edit" is worse for user experience

**Comment by HACO8888** [comment]
OK, I change to SEND.

**Review by banahaker — APPROVED** [review]
Good to merge!

**Pull request merged**
